### ISSUE TITLE
Type 'TFunctionResult' is not assignable to type 'ReactNode' on React 18

### ISSUE THREAD

**Issue by MonstraG** [i18next/react-i18next#1476]
## 🐛 Bug Report

After updating to React 18, following code gives a typescript error:
```tsx
<title>{t("common:title")}</title>
       ^^^^^^^^^^^^^^^^^^^
TS2322: Type 'TFunctionResult' is not assignable to type 'ReactNode'. 
  Type 'object' is not assignable to type 'ReactNode'. 
```

## To Reproduce

https://codesandbox.io/s/react-i18next-forked-ogdrcw?file=/src/app.tsx

## Expected behavior

No error

## Your Environment

```json
  "dependencies": {
    "i18next": "21.6.14",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-i18next": "11.16.2",
    "react-scripts": "5.0.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "typescript": "4.6.2"
  },
```

**Comment by Vinorcola** [comment]
Same fore me, but this comes after the following error that occures on the Provider (I suppose they are linked):

```
TS2322: Type '{ children: Element; i18n: i18n; }' is not assignable to type 'IntrinsicAttributes & I18nextProviderProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & I18nextProviderProps'.
    56 |
    57 |     return (
  > 58 |         <I18nextProvider i18n={i18next}>
       |          ^^^^^^^^^^^^^^^
```

**Comment by tiarebalbi** [comment]
+1 a really ugly workaround just to unblock dev.

```tsx
const { t } = useTranslation();
const x = (key: string) => t(key) as string || undefined;
<span>{x('key')}</span>
```

**Comment by akunzai** [comment]
I think this maybe caused by [Remove {} from ReactFragment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56026)

May we should add ReactNode to the `TFunctionResult`?

```ts
type TFunctionResult = string | object | Array<string | object> | undefined | null | ReactNode;
```

**Comment by guoyunhe** [comment]
Same problem here. Can you fix it?

**Comment by akunzai** [comment]
I am not a super TypeScript user, but I will try to fire a PR. It would be nice if any TypeScript experts can give me advice.

**Comment by adrai** [comment]
v11.16.4 fixes this

**Comment by Fallup** [comment]
> v11.16.4 fixes this

I'm on:
```
"react-i18next": "11.16.9",
"i18next": "21.8.1",
"react": "18.1.0",
"@types/react": "18.0.9",
"typescript": "4.6.4"
```

And issue is still there. 
Deleted the `package.lock` just in case something did not get populated correctly and checked that the fix applied in #1480 is there but the issue still exists. I wonder if that is caused by the latest TS version or what.

**Comment by adrai** [comment]
> > v11.16.4 fixes this
> 
> I'm on:
> 
> ```
> "react-i18next": "11.16.9",
> "i18next": "21.8.1",
> "react": "18.1.0",
> "@types/react": "18.0.9",
> "typescript": "4.6.4"
> ```
> 
> And issue is still there. Deleted the `package.lock` just in case something did not get populated correctly and checked that the fix applied in #1480 is there but the issue still exists. I wonder if that is caused by the latest TS version or what.

@Fallup please provide a reproducible example

**Comment by Fallup** [comment]
> > > v11.16.4 fixes this
> > 
> > 
> > I'm on:
> > ```
> > "react-i18next": "11.16.9",
> > "i18next": "21.8.1",
> > "react": "18.1.0",
> > "@types/react": "18.0.9",
> > "typescript": "4.6.4"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And issue is still there. Deleted the `package.lock` just in case something did not get populated correctly and checked that the fix applied in #1480 is there but the issue still exists. I wonder if that is caused by the latest TS version or what.
> 
> @Fallup please provide a reproducible example

As I tried to create a codesanbox example I finally noticed the issue I was missing. Import in my file was :
```
import { t } from 'i18next'
```
instead of the `useTranslation` hook from `react-i18next`.

Sorry for the false alarm, the #1480   works as expected 👍

**Comment by EyMaddis** [comment]
I think this is only fixed in a specific TS version or why is the file called `ts4.1/index.d.ts` ? At least for me on Typescript 4.3 and 11.18.0 it still breaks the same way

**Comment by horne3754sg** [comment]
I have the same issue and want to add that `import {t} from 'i18next';` works for me too. The type error disappears. 

So it looks like the hook is still incorrectly typed for React 18.

**Comment by adrai** [comment]
@pedrodurek can you confirm?

**Comment by pedrodurek** [comment]
Hey @horne3754sg, I tested it here, and it's working perfectly. Could you share a minimalistic version of your application, so I can help you?

**Comment by horne3754sg** [comment]
Hey @pedrodurek, I made a default react native TypeScript repo and just added a single component and `i18next`, `react-i18next`.

The version of TypeScript that Vscode is using is `4.7.3` but I also set it to the default version 4.4.4 that react native sets as its minimum and still got the same error.

The repo is here: https://github.com/horne3754sg/test-i18n-react-native

There is no need to run it, just install everything and maybe restart TypeScript.

React 18 changed the props of children and removed object.

Hope this helps :-)

![image](https://user-images.githubusercontent.com/2529445/180199679-f5249edc-e2bc-4f25-bcce-67f2744a661f.png)

**Comment by MonstraG** [comment]
> EDIT: I noticed that it is only happending because I was passing down the translation function as a prop and used the type `TFunction` for the prop. What is the correct way to do this?

Can confirm, happens when passing t into a function.

**Comment by AKclown** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/33648653/182988100-4cf64f51-9f38-45f1-a6d7-a50efcfd147e.png)

![image](https://user-images.githubusercontent.com/33648653/182988086-dc7137c1-462e-416d-a981-913a5463122f.png)

![image](https://user-images.githubusercontent.com/33648653/182988030-a6baa961-ba18-427d-b960-cfbf4261a2df.png)

**Comment by alnaranjo** [comment]
Hi,

I'm still experiencing this issue when using `t` from `gatsby-plugin-react-i18next`

```
"gatsby": "4.24.4",
"gatsby-plugin-react-i18next": "2.0.4",
"i18next": "22.0.2",
"react-i18next": "12.0.0",
```
<img width="972" alt="Screen Shot 2022-10-21 at 12 47 55" src="https://user-images.githubusercontent.com/8637151/197247836-3c5e1640-b21b-471f-8918-645408c884ea.png">

**Comment by alnaranjo** [comment]
Raised an issue here https://github.com/microapps/gatsby-plugin-react-i18next/issues/160

**Comment by moinulmoin** [comment]
I am still facing this issue in typescript 4.9.4
