### ISSUE TITLE
withTranslation - Type error: Type 'TFunctionResult' is not assignable to type 'ReactNode'

### ISSUE THREAD

**Issue by MarcelGeo** [i18next/react-i18next#1559]
[Type error: Type 'TFunctionResult' is not assignable to type 'ReactNode'](https://github.com/i18next/next-i18next/issues/1795#top)

This typescript error is not fixed by using withTranslation HOC.

**Comment by manwaring** [comment]
I'm getting the same error in the v12 release for the `t` function from `useTranslation` hook

**Comment by denizguzel** [comment]
Similar error here with the v12 release,

`Type 'DefaultTFuncReturn' is not assignable to type 'ReactNode'.`

**Comment by adrai** [comment]
fyi: https://github.com/i18next/i18next/issues/1852

**Comment by meyfa** [comment]
> Similar error here with the v12 release

See https://www.i18next.com/overview/typescript for how to add the required type definitions. This will make the error go away. But more importantly, i18next will now ensure you don't pass arbitrary strings to the `t` function that are not part of your translations. The feature was implemented here: https://github.com/i18next/i18next/pull/1775

By the way, thanks to everyone who made this happen! This is awesome! Finally we can statically ensure correct usage of the `t` function 🎉

**Comment by SergioTx** [comment]
And what if you need to pass "arbitrary strings" or at least strings formed by concatenation?

Something like:

```ts
function component(props: {stringProp: string}) {
  const {t} = useTranslation(myNs);
  return <div>{t(props.stringProp)}</div>
}
```

To strictly type all strings is not always an option.

Thank you!

**Comment by meyfa** [comment]
@SergioTx I think it makes sense to refactor such that the props are already translated. If this is not an option, you could use `as any` to evade type checking. Having the `any` type assertion there would at least clearly indicate to any future reader that the code is not actually safe.

**Comment by florianbepunkt** [comment]
Is there any way to disable type-checking here? In our translation workflow, we define the keys in code first with a default value... and then the translation keys are extracted by and automated process. So we have code-first approach when it comes to the keys, while the typescript docs effectively describe a translation-first approach, where the translation keys already exists in a JSON file.

**Comment by adrai** [comment]
> Is there any way to disable type-checking here? In our translation workflow, we define the keys in code first with a default value... and then the translation keys are extracted by and automated process. So we have code-first approach when it comes to the keys, while the typescript docs effectively describe a translation-first approach, where the translation keys already exists in a JSON file.

https://github.com/i18next/i18next/pull/1853#issuecomment-1291606531

**Comment by adrai** [comment]
can you try with i18next v22.0.3?

**Comment by karesztrk** [comment]
> can you try with i18next v22.0.3?

It works now. No compilation errors.

**Comment by adrai** [comment]
can you try with i18next v22.0.3?

**Comment by adrai** [comment]
@MarcelGeo  ?

**Comment by kirill-linnik** [comment]
I have the same problem with 22.0.4:
`TS2322: Type 'DefaultTFuncReturn' is not assignable to type 'string | ReactElement<any, string | JSXElementConstructor<any>> | undefined'.`
as a workaround, it looks like I should wrap all function invocation into `<></>`, which is a bit painful for a bit project. is there any other way fixing it?

**Comment by adrai** [comment]
> I have the same problem with 22.0.4:
> 
> `TS2322: Type 'DefaultTFuncReturn' is not assignable to type 'string | ReactElement<any, string | JSXElementConstructor<any>> | undefined'.`
> 
> as a workaround, it looks like I should wrap all function invocation into `<></>`, which is a bit painful for a bit project. is there any other way fixing it?

Can you create a reproducible example an open a new issue?

**Comment by kirill-linnik** [comment]
> > I have the same problem with 22.0.4:
> > `TS2322: Type 'DefaultTFuncReturn' is not assignable to type 'string | ReactElement<any, string | JSXElementConstructor<any>> | undefined'.`
> > as a workaround, it looks like I should wrap all function invocation into `<></>`, which is a bit painful for a bit project. is there any other way fixing it?
> 
> Can you create a reproducible example an open a new issue?

hmm, now I'm a bit puzzled. it works nice in a sandbox:
![image](https://user-images.githubusercontent.com/15168102/198835144-4a3f01ed-45be-4077-9b26-f37db76b34cb.png)
but in my project (I even deleted `yarn.lock` to have it "all fresh"), I get totally different definition of `t`:
![image](https://user-images.githubusercontent.com/15168102/198835110-d6d91e28-343d-4ae6-82f9-0412302ed6a4.png)

    "i18next": "22.0.4",
    "i18next-browser-languagedetector": "7.0.0",
    "react-i18next": "12.0.0",

I'm puzzled a bit. any idea why could it be the case?

**Comment by kirill-linnik** [comment]
ok, screw sandbox, I made a demo on top of playground project: https://github.com/i18next/react-i18next/issues/1574

**Comment by pedrodurek** [comment]
Hey @kirill-linnik, it seems `message` don't accept `null`, but `t` function could return `null`. I'd advice to fallback to something else. E.g.: `t('key') ?? ''`

**Comment by badsyntax** [comment]
I'm seeing something similar. As as temporary workaround I've been able to "fix" this by overriding the `TFunction` interface in my `i18next.d.ts` file, to apply the following change:

```difff
- TDefaultResult extends DefaultTFuncReturn = string,
+ TDefaultResult extends string = string, 
```

<details><summary>In file `i18next.d.ts`:</summary>

```ts
import 'i18next';

declare module 'i18next' {
  interface TFunction<
    N extends Namespace = DefaultNamespace,
    TKPrefix = undefined
  > {
    <
      TKeys extends TFuncKey<N, TKPrefix> | TemplateStringsArray extends infer A
        ? A
        : never,
      TDefaultResult extends string = string,
      TInterpolationMap extends object = StringMap
    >(
      key: TKeys | TKeys[]
    ): TFuncReturn<N, TKeys, TDefaultResult, TKPrefix>;
    <
      TKeys extends TFuncKey<N, TKPrefix> | TemplateStringsArray extends infer A
        ? A
        : never,
      TDefaultResult extends stringWithObject = object,
      TInterpolationMap extends object = StringMap
    >(
      key: TKeys | TKeys[],
      options?: TOptions<TInterpolationMap> & {
        returnDetails: true;
        returnObjects: true;
      }
    ): TFunctionDetailedResult<TFuncReturn<N, TKeys, TDefaultResult, TKPrefix>>;
    <
      TKeys extends TFuncKey<N, TKPrefix> | TemplateStringsArray extends infer A
        ? A
        : never,
      TDefaultResult extends string = string,
      TInterpolationMap extends object = StringMap
    >(
      key: TKeys | TKeys[],
      options?: TOptions<TInterpolationMap> & { returnDetails: true }
    ): TFunctionDetailedResult<TFuncReturn<N, TKeys, TDefaultResult, TKPrefix>>;
    <
      TKeys extends TFuncKey<N, TKPrefix> | TemplateStringsArray extends infer A
        ? A
        : never,
      TDefaultResult extends stringWithObject = object,
      TInterpolationMap extends object = StringMap
    >(
      key: TKeys | TKeys[],
      options?: TOptions<TInterpolationMap> & { returnObjects: true }
    ): TFuncReturn<N, TKeys, TDefaultResult, TKPrefix>;
    <
      TKeys extends TFuncKey<N, TKPrefix> | TemplateStringsArray extends infer A
        ? A
        : never,
      TDefaultResult extends string = string,
      TInterpolationMap extends object = StringMap
    >(
      key: TKeys | TKeys[],
      options?: TOptions<TInterpolationMap>
    ): TFuncReturn<N, TKeys, TDefaultResult, TKPrefix>;
    <
      TKeys extends TFuncKey<N, TKPrefix> | TemplateStringsArray extends infer A
        ? A
        : never,
      TDefaultResult extends string = string,
      TInterpolationMap extends object = StringMap
    >(
      key: TKeys | TKeys[],
      defaultValue?: string,
      options?: TOptions<TInterpolationMap> | string
    ): TFuncReturn<N, TKeys, TDefaultResult, TKPrefix>;
  }
}
```

</details>

**Comment by kirill-linnik** [comment]
@badsyntax yeah, there are several ways to workaround it. I've decided to postpone the update until it is fixed properly

@pedrodurek seems like we need `t` to return `string` ;)

**Comment by pedrodurek** [comment]
If you have access to the `translation` files in build time and follow the instructions [here](https://www.i18next.com/), `t` function will always return the correct type (string).
Please take a look at our examples: https://github.com/i18next/react-i18next/tree/master/example/react-typescript, https://github.com/i18next/i18next/tree/master/examples/typescript

**Comment by is-jonreeves** [comment]
@pedrodurek we have also ran into this same issue while upgrading a few of our projects. For now I'm working around this with the following (based on the [comment here](https://github.com/i18next/i18next/issues/1852#issuecomment-1287120864)):

`types/react-i18next.d.ts`
```ts
import 'react-i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
      [key: string]: {
        [key: string]: string;
      };
    };
  }
}
```

We found that doing what the [docs suggested](https://react.i18next.com/latest/typescript#create-a-declaration-file) and importing all of our namespace/JSON files resulted in a painfully slow VSCode. Further more, our projects use `i18nHttpBackend` to load the translations at runtime, so having to import/hardcode these into the project would unnecessarily bloat our resulting bundle and defeat the purposes of async loading the translations.

For what its worth I was able to import these into the `d.ts` file instead and I suspect it might not affect the bundle that way, however as I said the typechecking really slowed down.
```ts
import common from '@/../public/static/locales/en/common.json';
import home from '@/../public/static/locales/en/home.json';
...

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
      common: typeof common;
      home: typeof home;
      ...
    };
  }
}
```

While the IDE prompts were nice (aside from the slowdown), I did run into a few other problems:
1. The `DefaultNS` doesn't appear to be taken into account and type errors appear, e.g...
```json
// common.json
{
  "errors": {
    "unexpected": "Unexpected error"
  }
}

// home.json
{
  "page": {
    "title": "Welcome"
  }
}
```
```ts
// Relying on DefaultNS (common)
const { t } = useTranslation('home', { useSuspense: true });

console.log(✅, t('page.title'))
console.log(❌, t('common:errors.unexpected'))
```
```ts
// Explicitly including "common"
const { t } = useTranslation([ 'common', 'home' ], { useSuspense: true });

console.log(✅, t('home:page.title'))
console.log(✅, t('common:errors.unexpected'))
```

2. We weren't able to use dynamic strings any more:
```ts
console.log(✅, t('common:dates.days.mon'))
console.log(❌, t(`common:dates.days.${day}`))
```

With all of this in mind, and realizing my usecases may be the minority, it would still be great to see a way to bypass/disable the typing requirements as an option. For now the workaround mentioned above will work for me. Hope its helpful to others.

**Comment by pedrodurek** [comment]
Hey @is-jonreeves.
```tsx
// Relying on DefaultNS (common)
const { t } = useTranslation('home', { useSuspense: true });

console.log(✅, t('page.title'))
console.log(❌, t('common:errors.unexpected'))
```
This pattern ☝️ is not supported due to compilation time constrains, I'd advice to explicitly include the "common" namespace. I'm working on some improvements that will allow us to do that, but it may require a lot of tests and benchmark.

```tsx
console.log(✅, t('common:dates.days.mon'))
console.log(❌, t(`common:dates.days.${day}`))
```
`day` here needs to be a literal value, not only a string, otherwise it won't be type-safe. For example:
```tsx
const day = 'today' as const;
// type inferred: 'today' instead of string
```
with union type:
```tsx
type Props = {
  day: 'today' | 'tomorrow' | 'yesterday';
}
const Component = ({day}: Props) => {
  console.log(✅, t(`common:dates.days.${day}`))
}
```

**Comment by adrai** [comment]
should be fixed with i18next v22.0.5

**Comment by Snouzy** [comment]
> should be fixed with i18next v22.0.5

nop. I still have this issue. 
![screenshot-2022-11-13_11h25m41s](https://user-images.githubusercontent.com/32961176/201517042-c8b0a8c7-524a-4d16-9b73-6d90d11521df.png)

**Comment by eiskalteschatten** [comment]
v22.0.5 didn't fix it for me unfortunately. I am still getting the following error and had to downgrade to 22.0.3:

```
Type 'DefaultTFuncReturn' is not assignable to type 'string | undefined'.
```

I'm using the following with Node 18.12.1:

```
"i18next": "^22.0.5",
"react-i18next": "^12.0.0",
"typescript": "^4.5.4"
```

**Comment by manuelpoelzl** [comment]
> v22.0.5 didn't fix it for me unfortunately. I am still getting the following error and had to downgrade to 22.0.3:
> 
> ```
> Type 'DefaultTFuncReturn' is not assignable to type 'string | undefined'.
> ```
> 
> I'm using the following with Node 18.12.1:
> 
> ```
> "i18next": "^22.0.5",
> "react-i18next": "^12.0.0",
> "typescript": "^4.8.4"
> ```
> 
> And if it helps, this is the project: https://github.com/eiskalteschatten/InOrdnung

Have the exact same problem.

**Comment by pedrodurek** [comment]
`t` function can return `null`, this behaviour is set by default, if you want to change it, set `returnNull` type to `false`.

```ts
// i18next.d.ts
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    returnNull: false;
    ...
  }
}
```

I also recommend updating your i18next configuration to behave accordantly. https://www.i18next.com/overview/configuration-options#translation-defaults

```ts
i18next.init({
  returnNull: false,
   ...
});
```

**Comment by schankam** [comment]
> v22.0.5 didn't fix it for me unfortunately. I am still getting the following error and had to downgrade to 22.0.3:
> 
> ```
> Type 'DefaultTFuncReturn' is not assignable to type 'string | undefined'.
> ```
> 
> I'm using the following with Node 18.12.1:
> 
> ```
> "i18next": "^22.0.5",
> "react-i18next": "^12.0.0",
> "typescript": "^4.8.4"
> ```
> 
> And if it helps, this is the project: https://github.com/eiskalteschatten/InOrdnung

Exactly the same issue for me

**Comment by schankam** [comment]
> `t` function can return `null`, this behaviour is set by default, if you want to change it, set `returnNull` type to `false`.
> 
> ```ts
> // i18next.d.ts
> import 'i18next';
> 
> declare module 'i18next' {
>   interface CustomTypeOptions {
>     returnNull: false;
>     ...
>   }
> }
> ```
> 
> I also recommend updating your i18next configuration to behave accordantly. https://www.i18next.com/overview/configuration-options#translation-defaults
> 
> ```ts
> i18next.init({
>   returnNull: false,
>    ...
> });
> ```

Does not seem to work for me...

```
    "i18next": "^22.0.5",
    "i18next-browser-languagedetector": "^7.0.1",
    "i18next-http-backend": "^2.0.1",
    "react-i18next": "^12.0.0",
```

**Comment by Willham12** [comment]
in my case changing `declare module 'react-i18next' ` --> `declare module 'i18next' ` did the trick ;D

**Comment by imransilvake** [comment]
doesn't work
```
// init i18n
i18n.use(initReactI18next)
	.init({
		returnNull: false,
		resources: { en, de },
		lng: 'en',
		keySeparator: '.',
		interpolation: { escapeValue: false }
	})
	.then();
```
<img width="961" alt="Screenshot 2022-11-28 at 17 04 10" src="https://user-images.githubusercontent.com/13087225/204324789-ece11583-ea02-4773-9be7-286836e2d736.png">

**Comment by kazhuravlev** [comment]
Until the problem not fixed, we can use some sort of crutch like:

```typescript
function useXTranslate() {
  const {t} = useTranslation()

  return {t: t<string>};
}
```

and replace `const { t } = useTranslate()` to `const { t } = useXTranslate()`

NOTE: possibly this is insane advice. I am playing with TS/JS for only 5 days. But this is working for my case. 🤣

**Comment by adrai** [comment]
> Until the problem not fixed, we can use some sort of crutch like:
> 
> 
> 
> ```typescript
> 
> function useXTranslate() {
> 
>   const {t} = useTranslation()
> 
> 
> 
>   return {t: t<string>};
> 
> }
> 
> ```
> 
> 
> 
> and replace `const { t } = useTranslate()` to `const { t } = useXTranslate()`
> 
> 
> 
> my versions of i18next
> 
> ```
> 
> ...
> 
>  "i18next": "22.4.5",
> 
>  "react-i18next": "12.1.1",
> 
> ...
> 
> ```
> 
> 
> 
> NOTE: possibly this is insane advice. I am playing with TS/JS for only 5 days. But this is working for my case. 🤣 

Have you tried with i18next v22.4.5 ?

**Comment by kazhuravlev** [comment]
@adrai I think yes, because my version is `22.4.5`. May this output will be more helpful:

```shell
$ npm ll | grep i18next                                                                                                                                                   
├── i18next-browser-languagedetector@7.0.1
├── i18next@22.4.5
├── react-i18next@12.1.1
```


This is looks like I use exactly `22.4.5`

**Comment by adrai** [comment]
a minimal reproducible example repository would help

**Comment by dmytro-hk** [comment]
Have the same issue

```
"i18next": "22.4.5",
"react-i18next": "12.1.1",
"react": "18.2.0",
```

<img width="883" alt="Снимок экрана 2022-12-13 в 20 52 03" src="https://user-images.githubusercontent.com/22588235/207419969-4f2410a7-19ac-4699-9232-dfdee0323e28.png">

**Comment by kazhuravlev** [comment]
@adrai https://github.com/kazhuravlev/i18next-is-broke-by-project/blob/master/src/App.tsx#L9

**Comment by kazhuravlev** [comment]
Almost all people in this thread is describe the same problem with type definitions. No new info in my case. 

If you need an additional info - feel free to ask.

**Comment by adrai** [comment]
> Almost all people in this thread is describe the same problem with type definitions. No new info in my case.
> 
> If you need an additional info - feel free to ask.

I don't see any `i18next.d.ts` file defining `returnNull: false;`: https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

<img width="609" alt="image" src="https://user-images.githubusercontent.com/1086194/207423395-f39cb8bf-c752-4da2-8c24-4eeee40e6eb0.png">

**Comment by kazhuravlev** [comment]
wow. [this](https://github.com/kazhuravlev/i18next-is-broke-by-project/blob/master/src/i18next.d.ts#L6) is working. thx. 

But also, I think that this functional should be working without additional manipulations around the code. Hope we will get a function that will return just a strings.

**Comment by adrai** [comment]
Like described, the t function is potentially returning null... but it might be in the next major version we will set the default for `returnNull` to `false` => https://github.com/i18next/i18next/issues/1884

**Comment by m-nathani** [comment]
> Like described, the t function is potentially returning null... but it might be in the next major version we will set the default for `returnNull` to `false` => [i18next/i18next#1884](https://github.com/i18next/i18next/issues/1884)

any expected date on when it could be released ? otherwise we can keep using the old version `22.0.6` ,

**Comment by adrai** [comment]
@m-nathani no ETA at the moment... waiting for @pedrodurek's feedback...
in the meantime set returnNull to false yourself https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

**Comment by m-nathani** [comment]
> @m-nathani no ETA at the moment... waiting for @pedrodurek's feedback...
> in the meantime set returnNull to false yourself https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

Sounds great.. thanks for the link 👍
