### ISSUE TITLE
Trans component alternative usage - wrong child number

### ISSUE THREAD

**Issue by Arcus16** [i18next/react-i18next#892]
**Describe the bug**
When I use Trans component like this https://react.i18next.com/latest/trans-component#alternative-usage . I have to set wrong child number to make it work properly.

**Occurs in react-i18next version**
10.11.0

**Case 1**
` <Trans  i18nKey={`modal:${textKey}`}>Hello! <br/> some text. </Trans>`
Translation string: `"surveyCreatedText": "Hello! <1/> some text."`
This case is ok.
**Case 2**
`components = [<br />]`
` <Trans i18nKey={`modal:${textKey}`} components={components} />`
Translation string: `"surveyCreatedText": "Hello! <1/> some text."`
Gives  "Hello! some text." without <br/>
**Case 3**
`components = [<br />]`
` <Trans i18nKey={`modal:${textKey}`} components={components} />`
Translation string: `"surveyCreatedText": "Hello! <0/> some text."`
Gives desired result and warning "Each child in a list should have a unique "key" prop. ..."

**Comment by jamuhl** [comment]
Case 2 is wrong for the translation as <br /> has index: 0 in the components array -> therefore when using components props and not children it should be like in case 3 -> not 100% sure why it gives a warning about each child ...

might be it runs into: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L172 every other case seems to set a key.

if you make case 3 with `components = [<br key='somekey' />]` does the warning go away?

**Comment by Arcus16** [comment]
@jamuhl  bingo, with `components = [<br key='somekey' />]` the warning goes away

**Comment by jamuhl** [comment]
will need to debug and will try to add a key if not set....

**Comment by jamuhl** [comment]
should be fixed in react-i18next@10.11.4

**Comment by zeckdude** [comment]
I'm still seeing the problem in version `11.8.13` :(

Here's my code:

```
<Trans
  i18nKey="subscribeHeadlineCostPerMonth"
  values={{
    monthlyPrice: 20,
  }}
  components={[<wbr />]}
/>
```

That gives me the `Each child in a list should have a unique "key" prop` warning.

When I add the key to the component in the array, the warning goes away, but it sounds like this was already fixed previously?
```
<Trans
  i18nKey="subscribeHeadlineCostPerMonth"
  values={{
    monthlyPrice: 20,
  }}
  components={[<wbr key="somekey" />]}
/>
```
