### ISSUE TITLE
Property 'reportNamespaces' is missing

### ISSUE THREAD

**Issue by jake5146** [i18next/react-i18next#952]
**Describe the bug**

Typescript + React 
The use of I18nextProvider causes the following error. 

![capture](https://user-images.githubusercontent.com/17232712/65744402-3fcc2280-e0c6-11e9-805d-916729c9b886.JPG)

It didn't happen on 10.11.0 version. 

**Occurs in react-i18next version**
npm version: 6.5.0
react-i18next version: 10.13.0

**To Reproduce**
Use I18nextProvider and pass custom configured i18n (as instructed on react-i18next website), and I get the above error.

**OS (please complete the following information):**

Windows

**Comment by rosskevin** [comment]
@jake5146 Please provide a snippet of code that reproduces the error. As a volunteer that only maintains ts definitions, I don't know what example you refer to on the docs site.

I would prefer this is submitted as a PR to the `test/typescript` usage tests. That will get you results faster than anything else.

**Comment by rosskevin** [comment]
@jake5146 reminder - please get back to me with your reproduction.

**Comment by jamuhl** [comment]
closing due inactivity

**Comment by evanyz** [comment]
Solving same issue

**Comment by evanyz** [comment]
Got same issue, solved by yarn remove i18next, then yarn add i18next

**Comment by httpete** [comment]
Got the same as was fixed same way in npm:

```
 npm uninstall i18next, then npm install i18next

**Comment by prolland006** [comment]
i tried to uninstall/install "i18next" and it does not fix the issue

**Comment by prolland006** [comment]
i saw that when it is work it used i18next/index.v4.d.ts so typescript V4 that is should not be normal. And when the issue appear it use i18next/index.ts. So the pb is solved when i use and old release of i18next that use typescript V4 but other issues appears !

**Comment by prolland006** [comment]
i found the solution you have to put it "moduleResolution": "node" int tsconfig instead of "moduleResolution": "bundler" !

**Comment by saewitz** [comment]
v14 makes this optional, try `"react-i18next": "^14.0.0"` and `"i18next": "^23.8.2"`
